spring:
  cloud:
    function:
      definition: messageConsumer;messageProducer
    stream:
      kafka:
        bindings:
          messageProducer-out-0:
            producer:
              configuration:
                value.serializer: com.example.demoapp.converters.GreetingSerializer
          messageConsumer-in-0:
            consumer:
              configuration:
                value.deserializer: com.example.demoapp.converters.GreetingDeSerializer
        binder:
          brokers: localhost:9092

      bindings:
        messageProducer-out-0:
          destination: message
          producer:
            useNativeEncoding: true # Enables using the custom serializer
        messageConsumer-in-0:
          destination: message
          consumer:
            use-native-decoding: true # Enables using the custom deserializer